spring:
  config:
    activate:
      on-profile: prod
    import: aws-parameterstore:/cloud-project-app/prod/

  datasource:
    url: ${URL}
    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

info:
  app:
    message: ${TEAM_NAME}

