spring:
  application:
    name: cloud-project

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never


logging:
  level:
    root: INFO

