spring:
  application:
    name: cloud-project

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
  info:
    env:
      enabled: true

logging:
  level:
    root: INFO

