spring:
  application:
    name: cloud-project
  cloud:
    aws:
      region:
        static: ap-northeast-2
      s3:
        bucket: cloud-project-sohyun-files
  servlet:
    multipart:
      max-request-size: 10MB

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
  info:
    env:
      enabled: true

logging:
  level:
    root: INFO

