spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://RDS-ENDPOINT:3306/memberdb
    username: admin
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

